[package]
name = "look_and_say_kata"
version = "0.1.0"
authors = ["riojack <ayjay122@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
